---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
# Set the working directory
setwd("D:\\Reporducible research\\Data")
# Load the file
activitydata <- read.csv("activity.csv", as.is = TRUE)

#Converting the date to a valid R date type.
activitydata$date <- as.Date(activitydata$date)

#Remove the NA values and store in filledactivity data set
filledactivity <- activitydata[complete.cases(activitydata), ]

```



## What is mean total number of steps taken per day?
```{r}

# Calculate the total number of steps taken per day
stepsperday <- aggregate(steps ~ date, filledactivity, sum)

# Create a histogram of no of steps per day
hist(stepsperday$steps, main = "Histogram of total number of steps per day", xlab = "Steps per day")

#Calculate mean and median steps per day 
round(mean(stepsperday$steps))

round(median(stepsperday$steps))

```

## What is the average daily activity pattern?

```{r}

# Calculate average steps per interval for all days 
avgstepsperinterval <- aggregate(steps ~ interval, filledactivity, mean)


# Plot the time series
plot(avgstepsperinterval$interval, avgstepsperinterval$steps, type='l', col=1, main="Average number of steps by Interval", xlab="Time Intervals", ylab="Average number of steps")

# Find the index and the maximum value
intervalidx <- which.max(avgstepsperinterval$steps)
avgstepsperinterval[intervalidx, ]$interval
round(avgstepsperinterval[intervalidx, ]$steps, digits = 1)

```

## Imputing missing values
```{r}
#Calculate the number of rows with missing values
missing_value_act <- activitydata[!complete.cases(activitydata), ]
nrow(missing_value_act)

# Loop thru all the rows of activity.
# Find the one with NA for steps.
# For each identify the interval for that row
# Identify the avg steps for that interval in the set avgstepsperinterval
# Substitute the NA values with that avg steps

for (i in 1:nrow(activitydata)) {
    if(is.na(activitydata$steps[i])) {
        val <- avgstepsperinterval$steps[which(avgstepsperinterval$interval == activitydata$interval[i])]
        activitydata$steps[i] <- val 
    }
}

# Compute aggregate steps per day with the imputed values
stepsperdayimpute <- aggregate(steps ~ date, activitydata, sum)

# Draw a histogram of the value 
hist(stepsperdayimpute$steps, main = "Histogram of total number of steps per day (IMPUTED)", xlab = "Steps per day")

# Compute the mean and median of the imputed value
# Calculate the mean and median of the total number of steps taken per day
round(mean(stepsperdayimpute$steps))

median(stepsperdayimpute$steps)

```
## Are there differences in activity patterns between weekdays and weekends?

```{r}

days <- weekdays(filledactivity$date)
weekend <- (days == "Saturday" | days == "Sunday")
dayfactor <- factor(weekend, labels = list("weekday", "weekend"))
filledactivity$daytype <- dayfactor

groupedactivity <- aggregate(filledactivity$steps, list(DayType = filledactivity$daytype, 
    Interval = filledactivity$interval), mean)
library(lattice)
xyplot(groupedactivity$x ~ groupedactivity$Interval | groupedactivity$DayType, layout = c(1, 
    2), xlab = "Interval", ylab = "Number of Steps", type = "l")



```
